"""build_trigger_index.py - generate Skills/00_triggers.md from frontmatter.

Reads every Skills/<name>-SKILL.md, checks its frontmatter against the
convention in Skills/README.md (name matching the file, a one-line
description, at least one quoted trigger), and writes the phrase-to-
procedure index. Output is deterministic, so a rerun with no procedure
changed rewrites nothing. Standard library only.

Usage:  python "Skills/tools/build_trigger_index.py"   (from anywhere)

Exit codes:
  0  index written, or already current (prints "written" or "unchanged")
  2  a procedure breaks the convention; the file and reason are printed and
     the existing index is left untouched
"""

import os
import re
import sys

SKILLS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(SKILLS, "00_triggers.md")
SUFFIX = "-SKILL.md"

HEADER = """# Procedure trigger index

<!-- GENERATED by Skills/tools/build_trigger_index.py from each procedure's
frontmatter. Never edit by hand: change the procedure and rerun. -->

When the user asks for something like a phrase below, open that procedure
and follow it. Phrases are examples; match the intent, not the wording.

| Procedure | What it is for | Trigger phrases |
|---|---|---|
"""


class Broken(Exception):
    pass


def frontmatter(path):
    """Return {name, description, triggers} from the file's frontmatter."""
    lines = open(path, encoding="utf-8-sig").read().splitlines()
    if not lines or lines[0].strip() != "---":
        raise Broken("no frontmatter: the first line must be ---")
    end = next((i for i in range(1, len(lines))
                if lines[i].strip() == "---"), None)
    if end is None:
        raise Broken("frontmatter never closed with ---")
    fm, key = {}, None
    for raw in lines[1:end]:
        if not raw.strip():
            continue
        item = re.match(r"^\s+-\s+(.*)$", raw)
        if item:
            if key != "triggers":
                continue          # a list under another key: not ours
            phrase = item.group(1).strip()
            q = re.match(r'^"(.+)"$', phrase) or re.match(r"^'(.+)'$", phrase)
            if not q:
                raise Broken("trigger not quoted: %s" % phrase)
            fm["triggers"].append(q.group(1))
            continue
        kv = re.match(r"^([A-Za-z][\w-]*):\s*(.*)$", raw)
        if kv:
            key, val = kv.group(1), kv.group(2).strip()
            if key == "triggers":
                if val:
                    raise Broken("triggers must be a list, one per line")
                fm["triggers"] = []
            elif key in ("name", "description"):
                if val in ("", ">", "|", ">-", "|-"):
                    raise Broken("%s must be one line, on the key's line"
                                 % key)
                fm[key] = val
            continue
        if key in ("name", "description"):
            raise Broken("%s must be one line" % key)
    for need in ("name", "description", "triggers"):
        if not fm.get(need):
            raise Broken("missing %s" % need)
    return fm


def cell(text):
    return text.replace("|", "\\|")


def build():
    rows, problems = [], []
    for fn in sorted(os.listdir(SKILLS)):
        if not fn.endswith(SUFFIX):
            continue
        try:
            fm = frontmatter(os.path.join(SKILLS, fn))
            if fm["name"] + SUFFIX != fn:
                raise Broken("name %r does not match the file name"
                             % fm["name"])
        except Broken as e:
            problems.append("%s: %s" % (fn, e))
            continue
        rows.append("| [%s](%s) | %s | %s |" % (
            fm["name"], fn, cell(fm["description"]),
            "; ".join('"%s"' % cell(t) for t in fm["triggers"])))
    return rows, problems


def main():
    rows, problems = build()
    if problems:
        for p in problems:
            print("BROKEN " + p)
        print("index left as it was; fix the frontmatter per Skills/README.md")
        sys.exit(2)
    text = HEADER + "\n".join(rows) + "\n"
    old = None
    if os.path.exists(INDEX):
        old = open(INDEX, encoding="utf-8").read()
    if old == text:
        print("unchanged: %d procedures" % len(rows))
        return
    with open(INDEX, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("written: %d procedures" % len(rows))


if __name__ == "__main__":
    main()
